### PR TITLE
NATIVE-385: Search placeholder

### PR DESCRIPTION
**Pull request by SimonVortkamp**

### CODE REVIEW

**Comment by steffenkleinle** [comment]
Please name your PRs `NATIVE-385: Xyz`

**Review by steffenkleinle — CHANGES_REQUESTED** [review]
~~@SimonVortkamp this should be in a separate PR in the locales repo, which is afterwards just pulled using git subtrees.~~
Edit: Nevermind, I'm stupid. Sorry!

**Review by steffenkleinle — APPROVED** [review]
Not sure if just `Search` is that good, but should be okay.

**Review by lulo4907 — COMMENTED** [review]
Why do we have only one de-language placeholder?

**Comment by steffenkleinle** [comment]
Because it's not yet translated and that takes some time. I guess we have to think about a workflow for the future if locales are involved though. Imo in this case it's not that bad because it's only a placeholder, but some other stuff should not be released if locales are not translated.

**Review by lulo4907 — APPROVED** [review]
approved: "Suche" is displayed

**Pull request merged**
